version: "3.8"

services:
  backend:
    build:
      context: ../.. # ✅ Use project root as build context
      dockerfile: deployment/prod/Dockerfile # ✅ Ensure Dockerfile path is correct
    image: my-backend-prod
    container_name: backend-prod
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    restart: always
